export const COUNTRY_ARG = 'Argentina';
export const countryList = [
  "Argentina",
  "Ecuador",
  "Uruguay",
  "Perú",
  "México",
  "Colombia",
  "Costa Rica",
  "USA",
  "Dinamarca",
  "España",
  "Mexico"
];
export const argentinaList = {
  country: "Argentina",
  region: [
    {
        "label": "Buenos aires",
        "value": "B",
        "abbreviation": "B",
        "alternateabb": "AR-B"
    },
    {
        "label": "Catamarca",
        "value": "K",
        "abbreviation": "K",
        "alternateabb": "AR-K"
    },
    {
        "label": "Chaco",
        "value": "H",
        "abbreviation": "H",
        "alternateabb": "AR-H"
    },
    {
        "label": "Chubut",
        "value": "U",
        "abbreviation": "U",
        "alternateabb": "AR-U"
    },
    {
        "label": "Cordoba",
        "value": "X",
        "abbreviation": "X",
        "alternateabb": "AR-X"
    },
    {
        "label": "Corrientes",
        "value": "W",
        "abbreviation": "W",
        "alternateabb": "AR-W"
    },
    {
        "label": "Entre Rios",
        "value": "E",
        "abbreviation": "E",
        "alternateabb": "AR-E"
    },
    {
        "label": "Formosa",
        "value": "P",
        "abbreviation": "P",
        "alternateabb": "AR-P"
    },
    {
        "label": "Jujuy",
        "value": "Y",
        "abbreviation": "Y",
        "alternateabb": "AR-Y"
    },
    {
        "label": "La Pampa",
        "value": "L",
        "abbreviation": "L",
        "alternateabb": "AR-L"
    },
    {
        "label": "La Rioja",
        "value": "F",
        "abbreviation": "F",
        "alternateabb": "AR-F"
    },
    {
        "label": "Mendoza",
        "value": "M",
        "abbreviation": "M",
        "alternateabb": "AR-M"
    },
    {
        "label": "Misiones",
        "value": "N",
        "abbreviation": "N",
        "alternateabb": "AR-N"
    },
    {
        "label": "Neuquén",
        "value": "Q",
        "abbreviation": "Q",
        "alternateabb": "AR-Q"
    },
    {
        "label": "Rio Negro",
        "value": "R",
        "abbreviation": "R",
        "alternateabb": "AR-R"
    },
    {
        "label": "Salta",
        "value": "A",
        "abbreviation": "A",
        "alternateabb": "AR-A"
    },
    {
        "label": "San Juan",
        "value": "J",
        "abbreviation": "J",
        "alternateabb": "AR-J"
    },
    {
        "label": "San Luis",
        "value": "D",
        "abbreviation": "D",
        "alternateabb": "AR-D"
    },
    {
        "label": "Santa Cruz",
        "value": "Z",
        "abbreviation": "Z",
        "alternateabb": "AR-Z"
    },
    {
        "label": "Santa fé",
        "value": "S",
        "abbreviation": "S",
        "alternateabb": "AR-S"
    },
    {
        "label": "Santiago del Estero",
        "value": "G",
        "abbreviation": "G",
        "alternateabb": "AR-G"
    },
    {
        "label": "Tierra del Fuego ",
        "value": "V",
        "abbreviation": "V",
        "alternateabb": "AR-V"
    },
    {
        "label": "Tucumán",
        "value": "T",
        "abbreviation": "T",
        "alternateabb": "AR-T"
    }
  ],
};

export const regionList = [
  {
    ...argentinaList
  },
  {
    country: "Ecuador",
    region: [
      "Azuay",
      "Bolívar",
      "Cañar",
      "Carchi",
      "Chimborazo",
      "Cotopaxi",
      "El Oro",
      "Esmeraldas",
      "Galápagos",
      "Guayas",
      "Imbabura",
      "Loja",
      "Los Ríos",
      "Manabí",
      "Morona Santiago",
      "Napo",
      "Orellana",
      "Pastaza",
      "Pichincha",
      "Santa Elena",
      "Santo Domingo de los Tsáchilas",
      "Sucumbíos",
      "Tungurahua",
      "Zamora Chinchipe",
    ],
  },
  {
    country: "Uruguay",
    region: [
      "Artigas",
      "Canelones",
      "Cerro Largo",
      "Colonia",
      "Durazno",
      "Flores",
      "Florida",
      "Lavallega",
      "Maldonado",
      "Montevideo",
      "Paysandú",
      "Rio Negro",
      "Rivera",
      "Rocha",
      "Salto",
      "San José",
      "Soriano",
      "Tacuarembó",
      "Treinta y Tres",
    ],
  },
  {
    country: "Perú",
    region: [
      "Amazonas",
      "Áncash",
      "Apruímac",
      "Arequipa",
      "Ayacucho",
      "Cajamarca",
      "Callao",
      "Cusco",
      "Huancavelica",
      "Huánuco",
      "Ica",
      "Junín",
      "La Libertad",
      "Lambayeque",
      "Lima",
      "Loreto",
      "Madre de Dios",
      "Moquegua",
      "Pasco",
      "Piura",
      "Puno",
      "San Martín",
      "Tacna",
      "Tumbes",
      "Ucayali",
    ],
  },
  {
    country: "México",
    region: [
      "Aguascalientes",
      "Baja California",
      "Baja California Sur",
      "Campeche",
      "Chiapas",
      "Chihuahua",
      "Ciudad de México",
      "Coahuila de Zaragoza",
      "Colima",
      "Durango",
      "Guanajuato",
      "Guerrero",
      "Hidalgo",
      "Jalisco",
      "México",
      "Michoacán de Ocampo",
      "Morelos",
      "Nayarit",
      "Nuevo León",
      "Oxaca",
      "Puebla",
      "Querétaro",
      "Quintana Roo",
      "San Luis Potosí",
      "Sinaloa",
      "Sonora",
      "Tabasco",
      "Tamaulipas",
      "Tlaxcala",
      "Veracruz de Ignacio de la Llave",
      "Yucatán",
      "Zacatecas",
    ],
  },
  {
    country: "Colombia",
    region: [
      "Amazonas",
      "Antioquia",
      "Arauca",
      "Atlántico",
      "Bogotá",
      "Bolívar",
      "Boyacá",
      "Caldas",
      "Caquetá",
      "Casanare",
      "Cauca",
      "Cesar",
      "Chocó",
      "Córdoba",
      "Cundinamarca",
      "Guainía",
      "Guaviare",
      "Huila",
      "La Guajira",
      "Magdalena",
      "Meta",
      "Nariño",
      "Norte de Santander",
      "Putumayo",
      "Quindío",
      "Risaralda",
      "San Andrés Y Providencia",
      "Santander",
      "Sucre",
      "Tolima",
      "Valle del Cuaca",
      "Vaupés",
      "Vichada",
    ],
  },
  {
    country: "Costa Rica",
    region: [
      "San José",
      "Alajuela",
      "Cartago",
      "Heredia",
      "Guanacaste",
      "Puntarenas",
      "Limón",
    ],
  },
  {
    country: "USA",
    region: [
      "Alabama",
      "Alaska",
      "Arizona",
      "Akransas",
      "California",
      "Carolina del Norte",
      "Carolina del Sur",
      "Colorado",
      "Connecticut",
      "Dakota del Norte",
      "Dakota del Sur",
      "Delaware",
      "Florida",
      "Georgia",
      "Hawái",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Luisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Míchigan",
      "Minesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Jersey",
      "New York",
      "New Hampshire",
      "Nuevo México",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "West Virginia",
      "Washington",
      "Wisconsin",
      "Wyoming",
    ],
  },
  {
    country: "Dinamarca",
    region: [
      "Ciudad de Copenhague (Byen København)",
      "Alrededores de Copenhague (Københavns omegn)",
      "Zelanda del norte (Nordsjælland)",
      "Este de Zelanda (Østsjælland)",
      "Selandia occidental y meridional (Vest- og Sydsjælland)",
      "Bornholm",
      "Fionia (Fyn)",
      "Jutlandia del Sur (Sydjylland)",
      "Este de Jutlandia (Østjylland)",
      "Jutlandia occidental (Vestjylland)",
      "Jutlandia del Norte (Nordjylland)",
    ],
  },
  {
    country: "España",
    region: [
      "Castelló",
      "Huelva",
      "Santa Cruz de Tenerife",
      "Palencia",
      "Guadalajara",
      "Segovia",
      "Zamora",
      "Madrid",
      "Cantabria",
      "Bizkaia",
      "Badajoz",
      "Huesca",
      "Lugo",
      "Soria",
      "Toledo",
      "Illes Balears",
      "Navarra",
      "Alacant",
      "Murcia",
      "Albacete",
      "Cáceres",
      "Ciudad Real",
      "Lleida",
      "Ávila",
      "Cádiz",
      "València",
      "Barcelona",
      "Cuenca",
      "Sevilla",
      "Valladolid",
      "Ceuta",
      "Córdoba",
      "León",
      "Jaén",
      "Málaga",
      "Burgos",
      "Gipuzcoa",
      "Salamanca",
      "Melilla",
      "Almería",
      "Ourense",
      "Tarragona",
      "Granada",
      "La Rioja",
      "Araba",
      "Girona",
      "Asturias",
      "Las Palmas",
      "Pontevedra",
      "A Coruña",
      "Teruel",
      "Zaragoza",
    ],
  },
  {
    country: "Mexico",
    region: [
      "Aguascalientes",
      "Baja California",
      "Baja California Sur",
      "Campeche",
      "Chiapas",
      "Chihuahua",
      "Coahuila de Zaragoza",
      "Colima",
      "Durango",
      "Estado de México",
      "Guanajuato",
      "Guerrero",
      "Hidalgo",
      "Jalisco",
      "Michoacán de Ocampo",
      "Morelos",
      "Nayarit",
      "Nuevo León",
      "Oaxaca",
      "Puebla",
      "Querétaro",
      "Quintana Roo",
      "San Luis Potosí",
      "Sinaloa",
      "Sonora",
      "Tabasco",
      "Tamaulipas",
      "Tlaxcala",
      "Veracruz de Ignacio de la Llave",
      "Yucatán",
      "Zacatecas",
    ],
  },
];
